//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UATControl.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Payload Type")]
        public string PayloadTypeSetting {
            get {
                return ((string)(this["PayloadTypeSetting"]));
            }
            set {
                this["PayloadTypeSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Address Qualifier")]
        public string AddressQualifierSetting {
            get {
                return ((string)(this["AddressQualifierSetting"]));
            }
            set {
                this["AddressQualifierSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Address")]
        public string AddressSetting {
            get {
                return ((string)(this["AddressSetting"]));
            }
            set {
                this["AddressSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lattitude")]
        public string LattitudeSetting {
            get {
                return ((string)(this["LattitudeSetting"]));
            }
            set {
                this["LattitudeSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Longitude")]
        public string LongitudeSetting {
            get {
                return ((string)(this["LongitudeSetting"]));
            }
            set {
                this["LongitudeSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AltitudeType")]
        public string AltTypeSetting {
            get {
                return ((string)(this["AltTypeSetting"]));
            }
            set {
                this["AltTypeSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Altitude")]
        public string AltitudeSetting {
            get {
                return ((string)(this["AltitudeSetting"]));
            }
            set {
                this["AltitudeSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NIC")]
        public string NICSetting {
            get {
                return ((string)(this["NICSetting"]));
            }
            set {
                this["NICSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AirGroundState")]
        public string AGSetting {
            get {
                return ((string)(this["AGSetting"]));
            }
            set {
                this["AGSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("N/S Velocity")]
        public string NVelocitySetting {
            get {
                return ((string)(this["NVelocitySetting"]));
            }
            set {
                this["NVelocitySetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E/W Velocity")]
        public string EVelocitySetting {
            get {
                return ((string)(this["EVelocitySetting"]));
            }
            set {
                this["EVelocitySetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vertical Velocity")]
        public string VertVelocitySetting {
            get {
                return ((string)(this["VertVelocitySetting"]));
            }
            set {
                this["VertVelocitySetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UTCCoupledSetting {
            get {
                return ((bool)(this["UTCCoupledSetting"]));
            }
            set {
                this["UTCCoupledSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Emitter Category")]
        public string EmitterSetting {
            get {
                return ((string)(this["EmitterSetting"]));
            }
            set {
                this["EmitterSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Call Sign")]
        public string CallSignSetting {
            get {
                return ((string)(this["CallSignSetting"]));
            }
            set {
                this["CallSignSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Emergency/ Priority")]
        public string PrioritySetting {
            get {
                return ((string)(this["PrioritySetting"]));
            }
            set {
                this["PrioritySetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SIL")]
        public string SILSetting {
            get {
                return ((string)(this["SILSetting"]));
            }
            set {
                this["SILSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transmit MSO")]
        public string MSOSetting {
            get {
                return ((string)(this["MSOSetting"]));
            }
            set {
                this["MSOSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Systen Design Assurance")]
        public string SDASetting {
            get {
                return ((string)(this["SDASetting"]));
            }
            set {
                this["SDASetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NAC P")]
        public string NACPSetting {
            get {
                return ((string)(this["NACPSetting"]));
            }
            set {
                this["NACPSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NAC V")]
        public string NACVSetting {
            get {
                return ((string)(this["NACVSetting"]));
            }
            set {
                this["NACVSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NICBAROSetting {
            get {
                return ((bool)(this["NICBAROSetting"]));
            }
            set {
                this["NICBAROSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Capability Class")]
        public string CapabilitySetting {
            get {
                return ((string)(this["CapabilitySetting"]));
            }
            set {
                this["CapabilitySetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Operational Modes")]
        public string OperationModeSetting {
            get {
                return ((string)(this["OperationModeSetting"]));
            }
            set {
                this["OperationModeSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CSIDSetting {
            get {
                return ((bool)(this["CSIDSetting"]));
            }
            set {
                this["CSIDSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SILSUPSetting {
            get {
                return ((bool)(this["SILSUPSetting"]));
            }
            set {
                this["SILSUPSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Geometric Vertical Accuracy")]
        public string GVASetting {
            get {
                return ((string)(this["GVASetting"]));
            }
            set {
                this["GVASetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AntennaSetting {
            get {
                return ((bool)(this["AntennaSetting"]));
            }
            set {
                this["AntennaSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NICSUPSetting {
            get {
                return ((bool)(this["NICSUPSetting"]));
            }
            set {
                this["NICSUPSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Secondary Altitude")]
        public string SecondAltSetting {
            get {
                return ((string)(this["SecondAltSetting"]));
            }
            set {
                this["SecondAltSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SATSetting {
            get {
                return ((bool)(this["SATSetting"]));
            }
            set {
                this["SATSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Selected Altitude")]
        public string SelectedAltSetting {
            get {
                return ((string)(this["SelectedAltSetting"]));
            }
            set {
                this["SelectedAltSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Barometric Pressure (-800mb)")]
        public string BaroPressureSetting {
            get {
                return ((string)(this["BaroPressureSetting"]));
            }
            set {
                this["BaroPressureSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Selected Heading")]
        public string SelHeadingSetting {
            get {
                return ((string)(this["SelHeadingSetting"]));
            }
            set {
                this["SelHeadingSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutopilotSetting {
            get {
                return ((bool)(this["AutopilotSetting"]));
            }
            set {
                this["AutopilotSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VNAVSetting {
            get {
                return ((bool)(this["VNAVSetting"]));
            }
            set {
                this["VNAVSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AltHoldSetting {
            get {
                return ((bool)(this["AltHoldSetting"]));
            }
            set {
                this["AltHoldSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ApproachSetting {
            get {
                return ((bool)(this["ApproachSetting"]));
            }
            set {
                this["ApproachSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LNAVSetting {
            get {
                return ((bool)(this["LNAVSetting"]));
            }
            set {
                this["LNAVSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lattitude")]
        public string ULatSetting {
            get {
                return ((string)(this["ULatSetting"]));
            }
            set {
                this["ULatSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Longitude")]
        public string ULongSetting {
            get {
                return ((string)(this["ULongSetting"]));
            }
            set {
                this["ULongSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UPosValidSetting {
            get {
                return ((bool)(this["UPosValidSetting"]));
            }
            set {
                this["UPosValidSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UUTCSetting {
            get {
                return ((bool)(this["UUTCSetting"]));
            }
            set {
                this["UUTCSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UAppDataSetting {
            get {
                return ((bool)(this["UAppDataSetting"]));
            }
            set {
                this["UAppDataSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Time Slot ID")]
        public string UTimeIDSetting {
            get {
                return ((string)(this["UTimeIDSetting"]));
            }
            set {
                this["UTimeIDSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TIS-B Site ID")]
        public string USiteIDSetting {
            get {
                return ((string)(this["USiteIDSetting"]));
            }
            set {
                this["USiteIDSetting"] = value;
            }
        }
    }
}
